const initialLang: any = {
  english: {
    en: "en",
    english: "english",
    announcement: "announcement",
    description: "description",
    new: "new",
    kh: "kh",
    khmer: "khmer",
    cn: "cn",
    chinese: "chinese",
    vn: "vn",
    vietnamese: "vietnamese",
    light: "light",
    dark: "dark",
    username: "username",
    password: "password",
    login: "login",
    logout: "logout",
    register: "register",
    confirm: "confirm",
    invalid: "invalid",
    already: "already",
    exist: "exist",
    cannot: "cannot",
    connect: "connect",
    server: "server",
    probably: "probably",
    you: "you",
    internet: "internet",
    error: "error",
    success: "success",
    email: "email",
    setting: "setting",
    settings: "settings",
    home: "home",
    clients: "clients",
    users: "users",
    app: "app",
    name: "name",
    phone: "phone",
    gender: "gender",
    bill: "bill",
    address: "address",
    delivery: "delivery",
    created: "created",
    updated: "updated",
    total: "total",
    clear: "clear",
    cancel: "cancel",
    download: "download",
    filter: "filter",
    male: "male",
    female: "female",
    none: "none",
    has: "has",
    no: "no",
    all: "all",
    getting: "getting",
    ok: "ok",
    broadcast: "broadcast",
    data: "data",
    code: "code",
    type: "type",
    role: "role",
    groups: "groups",
    details: "details",
    on_d: "on",
    by: "by",
    number: "number",
    receipt: "receipt",
    date: "date",
    save: "save",
    amount: "amount",
    temporary: "temporary",
    current: "current",
    earned: "earned",
    edit: "edit",
    earn: "earn",
    spent: "spent",
    offset: "offset",
    user: "user",
    remark: "remark",
    points: "points",
    check: "check",
    last: "last",
    now: "now",
    done: "done",
    report: "report",
    hold: "hold",
    resign: "resign",
    event: "event",
    of: "of",
    setup: "setup",
    this: "this",
    remain: "remain",
    event_s: "event",
    permissions: "permissions",
    year: "year",
    available: "available",
    title: "title",
    image: "image",
    adjustment_v: "adjustment",
    pending_pub: "pending",
    alert: "alert",
    compressing: "compressing",
    remaining: "remaining",
    published: "published",
    publish: "publish",
    search: "search",
    expired: "expired",
    most: "most",
    least: "least",
    adjust: "adjust",
    month: "month",
    web: "web",
    status: "status",
    member: "member",
    members: "members",
    confirmation: "confirmation",
    yes: "yes",
    no_a: "no",
    from_d: "from",
    to_d: "to",
    republish: "republish",
    "lastname (ENG)": "lastname (ENG)",
    "title (ENG)": "title (ENG)",
    "title (KH)": "title (KH)",
    "description (ENG)": "description (ENG)",
    "description (KH)": "description (KH)",
    "allow all": "allow all",
    "created date": "created date",
    "duplicated event title": "duplicated event title",
    "edit to republish": "edit to republish",
    "invalid email": "invalid email",
    "are you sure on creating this announcement?": "are you sure on creating this announcement?",
    "event setup_v": "event setup",
    "have access": "have access",
    "no access": "no access",
    "firstname (ENG)": "firstname (ENG)",
    "cannot find the events": "cannot find the events",
    "access right": "access right",
    "try to compress it and upload": "try to compress it and upload",
    "is added": "is added",
    "remain points": "remain points",
    "save as new event": "save as new event",
    "cannot find the announcements": "cannot find the announcements",
    "expiry date": "expiry date",
    "something went wrong while compressing": "something went wrong while compressing",
    "your file is too large (limit size is 1.8MB)": "Your file is too large (limit size is 1.8MB)",
    "client number": "number",
    "bill address": "bill address",
    "loyalty program dashboard": "loyalty program dashboard",
    "title is required": "title is required",
    "delivery address": "delivery address",
    "export excel": "export excel",
    "top 10 earn points members": "top 10 earn points members",
    "top 10 spent points members": "top 10 spent points members",
    "top 10 points members": "top 10 points members",
    "your file size": "your file size",
    "too large (limit size is 1.8MB)": "too large (limit size is 1.8MB)",
    "change image": "change image",
    "show all clients": "show all clients",
    "all clients": "all clients",
    "old password": "old password",
    "new members": "new members",
    "new password": "new password",
    "display name": "display name",
    "this year": "this year",
    "receipt number": "receipt number",
    "incorrect password": "incorrect password",
    "adjust point_v": "adjust point",
    "check last points now": "check last points now",
    "firstname (KH)": "firstname (KH)",
    "lastname (KH)": "lastname (KH)",
    "total points": "total points",
    "this month": "this month",
    "total members": "total members",
    "available members": "available members",
    "add new event": "add new event",
    "add new announcement": "add new announcement",
    "click to upload or drag and drop image here": "click to upload or drag and drop image here",
    "expired members": "expired members",
    "something went wrong": "something went wrong",
    "change password": "change password",
    "delete account": "delete account",
    "published_now": "publish now",
    "event setup": "event setup",
    "add new event now": "add new event now",
    "add new announcement now": "add new announcement now",
    "new event": "new event",
    "new announcement": "new announcement",
    "points report": "points report",
    "profile updated": "profile updated",
    "specified clients": "specified clients",
    "specific clients": "specific clients",
    "password is changed": "password is changed",
    "checking events": "checking events",
    "checking announcements": "checking announcements",
    "oop no events": "oop! no events",
    "oop no announcements": "oop! no announcements",
    "no data yet": "no data yet",
    "max remaining months": "max remaining months",
    "check last points record now": "check last points record now",
    "please consider checking last point record before adjusting points": "please consider checking last point record before adjusting points",
    "compress then upload": "compress then upload",
    "cannot connect to server, probably you have no internet connection or server down": "cannot connect to server, probably you have no internet connection or server down",
    "connect to": "connect to",
    "date filter": "date filter",
    "adjust point": "adjust point",
    "points history": "points history",
    "client list": "client list",
    "user list": "user list",
    "user account": "user account",
    "light theme": "light theme",
    "offset point": "offset point",
    "dark theme": "dark theme",
    "have no": "have no",
    "do not have account yet": "do not have account yet",
    "already have account": "already have account",
    "forgot password": "forgot password",
    "confirm password": "confirm password",
    "invalid username": "invalid username",
    "invalid name": "invalid name",
    "password does not match": "password does not match",
    "username already exist": "username already exist"
  },
  khmer: {
    en: "អង់គ្លេស",
    english: "អង់គ្លេស",
    kh: "ខ្មែរ",
    khmer: "ខ្មែរ",
    cn: "ចិន",
    code: "លេខកូដ",
    chinese: "ចិន",
    vn: "វៀតណាម",
    vietnamese: "វៀតណាម",
    light: "ភ្លឺ",
    edit: "កែប្រែ",
    dark: "ងងឹត",
    username: "ឈ្មោះប្រើប្រាស់",
    published: "ដាក់ផ្សព្វផ្សាយ",
    save: "រក្សាទុក",
    password: "ពាក្យសម្ងាត់",
    login: "ចូលប្រើប្រាស់",
    logout: "ចាកចេញ",
    register: "ចុះឈ្មោះ",
    confirm: "បញ្ជាក់",
    invalid: "មិនត្រឹមត្រូវ",
    already: "រួចហើយ",
    exist: "មាន",
    cannot: "មិនអាច",
    connect: "ភ្ជាប់",
    remaining: "នៅសល់",
    server: "ប្រព័ន្ធ",
    probably: "ប្រហែល",
    you: "អ្នក",
    type: "ប្រភេទ",
    role: "តួនាទី",
    confirmation: "សារបញ្ជាក់",
    groups: "ក្រុម",
    internet: "អុីនធើណេត",
    error: "មានបញ្ហា",
    member: "សមាជិក",
    success: "ជោគជ័យ",
    setting: "ការកំណត់",
    ok: "យល់ព្រម",
    settings: "ការកំណត់",
    home: "​ទំព័រដើម",
    clients: "អតិថិជន",
    users: "អ្នកប្រើប្រាស់",
    app: "កម្មវិធីទូរស័ព្ទ",
    name: "ឈ្មោះ",
    phone: "ទូរស័ព្ទទាក់ទង",
    gender: "ភេទ",
    bill: "វិក្កយបត្រ",
    web: "គេហទំព័រ",
    address: "អសយដ្ឋាន",
    delivery: "ដឹកជញ្ជូន",
    created: "បង្កើត",
    email: "អុីមែល",
    of: "នៃ",
    updated: "កែប្រែ",
    alert: "ដំណឹងបញ្ហា",
    publish: "ផ្សព្វផ្សាយ",
    total: "សរុប",
    clear: "សំអាត",
    download: "ទាញយក",
    cancel: "បោះបង់",
    filter: "ច្រោះ",
    male: "ប្រុស",
    female: "ស្រី",
    none: "មិនបានកំណត់",
    has: "មាន",
    no: "គ្មាន",
    all: "ទាំងអស់",
    getting: "កំពុងទទួល",
    data: "ទិន្នន័យ",
    details: "ពត៌មានលម្អិត",
    on_d: "នៅថ្ងៃ",
    by: "ដោយ",
    number: "លេខសម្គាល់",
    receipt: "វិក្កយបត្រ",
    date: "កាលបរិច្ឆេទ",
    amount: "ចំនួនទឹកប្រាក់",
    image: "រូបភាព",
    compressing: "កំពុងដំណើរការពង្រួមទំហំរូបភាព",
    from_d: "ចាប់ពីថ្ងៃ",
    to_d: "ដល់ថ្ងៃ",
    temporary: "បណ្តោះអាសន្ន",
    new: "ថ្មី",
    current: "បច្ចុប្បន្ន",
    earned: "ទទួលបាន",
    earn: "ទទួល",
    adjust: "កែតម្រូវ",
    spent: "បានចាយ",
    remain: "នៅសល់",
    offset: "បានសម្រួល",
    user: "អ្នកប្រើប្រាស់",
    remark: "កំណត់សម្គាល់",
    points: "ពិន្ទុ",
    check: "ពិនិត្យមើល",
    last: "ចុងក្រោយ",
    now: "ឥឡូវ",
    done: "រួចរាល់",
    report: "របាយការណ៍",
    hold: "hold",
    resign: "resign",
    event: "កម្មវិធីផ្សេងៗ",
    event_s: "កម្មវិធី",
    setup: "ការរៀបចំ",
    this: "នេះ",
    month: "ខែ",
    permissions: "សិទ្ធប្រើប្រាស់",
    most: "ច្រើនបំផុត",
    search: "ស្វែងរក",
    least: "តិចបំផុត",
    pending_pub: "មិនទាន់ផ្សព្វផ្សាយ",
    year: "ឆ្នាំ",
    available: "នៅសុពលភាព",
    adjustment_v: "បានកែតម្រូវ",
    expired: "ផុតសុពលភាព",
    yes: "បាទ/ចាស",
    no_a: "ទេ",
    broadcast: "ការផ្សព្វផ្សាយ",
    announcement: "សេចក្តីជូនដំណឹង",
    description: "បរិយាយ",
    members: "សមាជិក",
    status: "ស្ថានភាព",
    title: "ចំណងជើង",
    "date filter": "ច្រោះរកតាមកាលបរិច្ឆេទ",
    "loyalty program dashboard": "តារាងសង្ខេបពត៌មានអតិថិជនដែលជាសមាជិក",
    "checking events": "ពិនិត្យរកកម្មវិធីផ្សព្វផ្សាយ",
    "checking announcements": "ពិនិត្យរកសេចក្តីជូនដំណឹង",
    "access right": "សិទ្ធិប្រើប្រាស់",
    "cannot find the announcements": "មិនឃើញសេចក្តីជូនដំណឹងតាមការស្វែងរក",
    "cannot find the events": "មិនឃើញកម្មវិធីផ្សព្វផ្សាយតាមការស្វែងរក",
    "offset point": "ពិន្ទុដែលបានសម្រួល",
    "title (ENG)": "ចំណងជើង (អង់គ្លេស)",
    "title (KH)": "ចំណងជើង (ខ្មែរ)",
    "oop no events": "មិនទាន់មានកម្មវិធីផ្សព្វផ្សាយ",
    "save as new event": "រក្សាទុកជាកម្មវីធីផ្សព្វផ្សាយថ្មី",
    "description (ENG)": "បរិយាយ (អង់គ្លេស)",
    "description (KH)": "បរិយាយ (ខ្មែរ)",
    "oop no announcements": "មិនទាន់មានសេចក្តីជូនដំណឹង",
    "add new event now": "ដាក់បញ្ចូលកម្មវិធីផ្សព្វផ្សាយ",
    "add new announcement": "ដាក់បញ្ចូលសេចក្តីជូនដំណឹង",
    "add new announcement now": "ដាក់បញ្ចូលសេចក្តីជូនដំណឹង",
    "change password": "ប្តូរពាក្យសម្ងាត់",
    "invalid name": "ឈ្មោះមិនត្រឹមត្រូវ",
    "invalid email": "អុីមែលមិនត្រឹមត្រូវ",
    "delete account": "លុបគណនី",
    "display name": "ឈ្មោះបង្ហាញ",
    "new event": "កម្មវិធីផ្សព្វផ្សាយថ្មី",
    "are you sure on creating this announcement?": "អ្នកពិតជាសំរេចចិត្តបង្កើតសេចក្តីជូនដំណឹងមួយនេះ?",
    "new announcement": "សេចក្តីជូនដំណឹងថ្មី",
    "old password": "ពាក្យសម្ងាត់ចាស់",
    "is added": "ត្រូវបានដាក់បញ្ចូលរួចរាល់",
    "lastname (ENG)": "គោត្តនាម (អង់គ្លេស)",
    "click to upload or drag and drop image here": "ចុចទីនេះ ឬអូសរូបភាពទម្លាក់នៅទីនេះដើម្បីបញ្ចូលរូបភាព",
    "lastname (KH)": "គោត្តនាម (ខ្មែរ)",
    "event setup_v": "កំណត់កម្មវិធីផ្សព្វផ្សាយ",
    "change image": "ប្តូរូបភាព",
    "something went wrong while compressing": "មានបញ្ហាកើតឡើងនៅពេលធ្វើការពង្រួមទំហំរូបភាព",
    "your file is too large (limit size is 1.8MB)": "ទំហំរូបភាពធំលើសកំណត់ (ទំហំកំណត់ធំបំផុតត្រឹម 1.8MB)",
    "expiry date": "ថ្ងៃផុតសុពលភាព",
    "show all clients": "បង្ហាញសមាជិកទាំងអស់",
    "export excel": "ទាញយកជាឯកសា excel",
    "remain points": "ពិន្ទុនៅសល់",
    "top 10 earn points members": "សមាជិកដែលសន្សំពិន្ទុបានច្រើនជាងគេទាំង 10",
    "add new event": "បញ្ចូលកម្មវិធីផ្សព្វផ្សាយថ្មី",
    "all clients": "សមាជិកទាំងអស់",
    "top 10 spent points members": "សមាជិកចាយពិន្ទុអស់ច្រើនជាងគេទាំង 10",
    "top 10 points members": "សាមជិកដែលមានពិន្ទុខ្ពស់ជាងគេទាំង 10",
    "new password": "ពាក្យសម្ងាត់ថ្មី",
    "try to compress it and upload": "សាកល្បងពង្រួមទំហំរូបភាព រួចរក្សាទុក",
    "compress then upload": "ពង្រួមហើយរក្សាទុក",
    "new members": "សមាជិកថ្មី",
    "max remaining months": "ចំនួនខែនៅសល់ច្រើនបំផុត",
    "receipt number": "លេខវិក្កយបត្រ",
    "check last points now": "ពិនិត្យមើលពិន្ទុចុងក្រោយ",
    "bill address": "អសយដ្ឋានលើវិក្កយបត្រ",
    "delivery address": "អសយដ្ឋានដឹកជញ្ជូន",
    "title is required": "ទាមទារត្រូវមានចំណងជើង",
    "total points": "ពិន្ទុសរុប",
    "total members": "សមាជិកសរុប",
    "available members": "សមាជិកនៅសុពលភាព",
    "expired members": "សមាជិកផុតសុពលភាព",
    "this year": "ឆ្នាំនេះ",
    "profile updated": "ពត៌មានផ្ទាល់ខ្លួនបានកែប្រែរួចរាល់",
    "password is changed": "ពាក្យសម្ងាត់បានផ្លាស់ប្តូរួចរាល់",
    "this month": "ខែនេះ",
    "have access": "មានសិទ្ធិ",
    "no access": "គ្មានសិទ្ធិ",
    "allow all": "អនុញ្ញាតិទាំងអស់",
    "something went wrong": "មានបញ្ហាកើតឡើង",
    "event setup": "ការផ្សព្វផ្សាយកម្មវិធីផ្សេងៗ",
    "no data yet": "មិនទាន់មានទិន្នន័យ",
    "your file size": "រូបភាពរបស់អ្នកមានទំហំ",
    "firstname (ENG)": "នាម (អង់គ្លេស)",
    "firstname (KH)": "នាម (ខ្មែរ)",
    "incorrect password": "ពាក្យសំងាត់មិនត្រឹមត្រូវ",
    "too large (limit size is 1.8MB)": "ធំលើសកំណត់ (ទំហំកំណត់ធំបំផុតត្រឹម 1.8MB)",
    "client number": "លេខសមាជិក",
    "points report": "របាយការណ៍ពិន្ទុ",
    "specified clients": "សមាជិកតាមការច្រោះ",
    "specific clients": "សមាជិកតាមការច្រោះ",
    "check last points record now": "ពិនិត្យមើលពិន្ទុចុងក្រោយ",
    "please consider checking last point record before adjusting points": "សូមធ្វើការពិនិត្យមើលទិន្នន័យពិន្ទុចុងក្រោយ មុនធ្វើការថែម ឬថយពិន្ទុ",
    "cannot connect to server, probably you have no internet connection or server down": "មិនអាចភ្ជាប់ទៅកាន់ប្រព័ន្ធទិន្នន័យ អាចមកពីប្រព័ន្ធមានបញ្ហា ឬ ម៉ាសុីនរបស់អ្នកគ្មានអុីនធើនែត",
    "connect to": "ភ្ជាប់ទៅកាន់",
    "adjust point": "ពិន្ទុបានកែតម្រូវ",
    "adjust point_v": "កែតម្រូវពិន្ទុ",
    "points history": "ប្រវត្តិពិន្ទុ",
    "client list": "បញ្ជីឈ្មោះអតិថិជន",
    "user list": "បញ្ជីឈ្មោះអ្នកប្រើប្រាស់",
    "user account": "គណនីអ្នកប្រើប្រាស់",
    "light theme": "ផ្ទៃភ្លឺ",
    "dark theme": "ផ្ទៃងងឹត",
    "have no": "មិនមាន",
    "created date": "ថ្ងៃបង្កើត",
    "do not have account yet": "មិនទាន់មានគណនីនៅឡើយ",
    "already have account": "មានគណនីរួចហើយ",
    "forgot password": "ភ្លេចពាក្យសម្ងាត់",
    "confirm password": "បញ្ជាក់ពាក្យសម្ងាត់",
    "invalid username": "ឈ្មោះប្រើប្រាស់មិនត្រឹមត្រូវ",
    "duplicated event title": "ចំណងជើងមានរួចហើយ",
    "edit to republish": "ធ្វើការពិនិត្យកែប្រែដើម្បីផ្សព្វផ្សាយម្តងទៀត",
    "password does not match": "ពាក្យសម្ងាត់មិនផ្ទៀងផ្ទាត់",
    "published_now": "ផ្សព្វផ្សាយឥឡូវ",
    "username already exist": "ឈ្មោះអ្នកប្រើប្រាស់មានអ្នកប្រើហើយ"
  }
}
export default initialLang